"""ECS components and the data types around them.

Split across submodules: `enums` (StatusType/EffectType/ShopOfferKind/InputAction plus
the YAML-loaded ItemType/SpellType and controller bindings), `configs` (the parsed
YAML-config TypedDicts), `components` (the ECS component dataclasses and the spell-effect
model), and `utils` (small shared type aliases). Public names are re-exported here so
callers import them as `from src.components import X`.
"""

from src.components.components import (
    AI,
    Actor,
    CastVisual,
    ChaseTag,
    Configuration,
    DamageModifier,
    Effect,
    Enemy,
    EnemyAbility,
    FieldOfView,
    FleeTag,
    GuardTag,
    Inventory,
    Item,
    Keybindings,
    KnownRecipes,
    Loot,
    LootDrop,
    MessageLog,
    Modal,
    Particle,
    PatrolTag,
    PlayerTag,
    Point,
    Position,
    Projectile,
    Renderable,
    RunStats,
    ScreenFlash,
    Shopkeeper,
    ShopOffer,
    SpellInventory,
    Stats,
    StatusEffects,
    TargetingReticle,
    UIState,
)
from src.components.configs import (
    EnemyConfig,
    GameConfigs,
    IngredientConfig,
    RecipeConfig,
    ShopConfig,
    SpellConfig,
    TileConfig,
)
from src.components.enums import (
    ControllerBinding,
    EffectType,
    InputAction,
    ItemType,
    ShopOfferKind,
    SpellType,
    StatusType,
    default_controller_bindings,
)
from src.components.utils import Message, MessageSegment

__all__ = [
    'AI',
    'Actor',
    'CastVisual',
    'ChaseTag',
    'Configuration',
    'ControllerBinding',
    'DamageModifier',
    'Effect',
    'EffectType',
    'Enemy',
    'EnemyAbility',
    'EnemyConfig',
    'FieldOfView',
    'FleeTag',
    'GameConfigs',
    'GuardTag',
    'IngredientConfig',
    'InputAction',
    'Inventory',
    'Item',
    'ItemType',
    'Keybindings',
    'KnownRecipes',
    'Loot',
    'LootDrop',
    'Message',
    'MessageLog',
    'MessageSegment',
    'Modal',
    'Particle',
    'PatrolTag',
    'PlayerTag',
    'Point',
    'Position',
    'Projectile',
    'RecipeConfig',
    'Renderable',
    'RunStats',
    'ScreenFlash',
    'ShopConfig',
    'ShopOffer',
    'ShopOfferKind',
    'Shopkeeper',
    'SpellConfig',
    'SpellInventory',
    'SpellType',
    'Stats',
    'StatusEffects',
    'StatusType',
    'TargetingReticle',
    'TileConfig',
    'UIState',
    'default_controller_bindings',
]
